### ISSUE TITLE
openNlp don’t return valid result in pdf

### ISSUE THREAD

**Issue by HADDADENICAR** [spinscale/elasticsearch-ingest-opennlp#25] opened 2018-03-13 16:26 UTC
Hi,
I've succeded recently to load a pdf in elasticsearch using your plugin, however the results wasn't as good as i expected : 
**the  attachment.person contains Mysql, and i 've another names that haven't been returned by the plugin.
**the attachment.dates works fine expect it returns also dates with comma before or after for example "2014-"
**attachement.Location also is far from normal ; it returns for just partial one " Avenue el l" while it is Avenue el l'UMA.

this is the pdf  's view : 

![image](https://user-images.githubusercontent.com/35377776/37355112-79118538-26e3-11e8-865d-69c1a0e3cb96.png)

and this is the fields i get : 

![image](https://user-images.githubusercontent.com/35377776/37355132-855087ae-26e3-11e8-8916-71ac3bf02b8c.png)

What do you suggest to  fix ?
Is there any configuration to add ?

**Comment by spinscale** [comment] 2018-03-15 23:14
please do not attach screenshots, but real JSON to issues, this makes it incredible hard to read and you are immediately excluding people (color blind, visually impaired) who will never find out what the issue is.

all of this depends on the models being used in combination with the tokenizers. So you can replace the models with own ones or language specific ones. I just packaged the default ones.

This is more of an opennlp issue, rather than a plugin issue. Closing.

**Closed as completed by spinscale** 2018-03-15 23:14 UTC
